# ============================================
# 1. CONFIGURACION DEL SERVIDOR
# ============================================
server.port=8080

# ============================================
# 2. CONFIGURACION DE POSTGRESQL (MULTI-TENANT)
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/agendamiento_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# 3. CONFIGURACION DE JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# 4. CREDENCIALES WHATSAPP CLOUD API (HANDSHAKE)
# ============================================
whatsapp.verification.token=MiTokenSecretoDelHackathon2026
whatsapp.api.token=EAAqjlfsIrEkBR0ZCGxS0wmjh7E44NTeLcRm28tdG55FZBjG3f8kVa4H8j0ccKeKZAdbtZCsNAZBLM7OrxBvbiOk9GiXqZAqaEFLakvGghTsZCXSbjV5vvNGRisdmDEkaQ2zHwZCiZC9jd8GsiUrvJiEe0F2ajHeyB8IIDkxMhg4LZB6rV3hbKjEBRgZACet8VzfTNCtRQPW5VSc1e4R3BaPhZCVnVIoZBOGCC2jZCh4JYn1gGWi39lAAPwEJDpHnCgbmymBakzG0NT8Ec118ttLIGKuOxZC3ZB06UmJYZB7Qrt1TtygZDZD

# ============================================
# 5. CREDENCIALES STRIPE API
# ============================================
stripe.api.key=CAMBIAR_POR_LLAVE_REAL
stripe.webhook.secret=CAMBIAR_POR_FIRMA_REAL