# ============================================
# 1. CONFIGURACION DEL SERVIDOR
# ============================================
server.port=8080

# ============================================
# 2. CONFIGURACION DE POSTGRESQL (MULTI-TENANT)
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/agendamiento_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# 3. CONFIGURACION DE JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# 4. CREDENCIALES WHATSAPP CLOUD API (HANDSHAKE)
# ============================================
whatsapp.verification.token=MiTokenSecretoDelHackathon2026
whatsapp.api.token=EAAqjlfsIrEkBRZCmkiLSwVjNFgU09sAU47KFFz4uL2TMt0Cmw4iSI4eZB29lvS7w4xeiSiFmTJbHIcEAaNDDdZBGbhUKXi1TkeXVkmx2cd0zLZCS3J6EyBH67RKga5qIboHLHX1Y0WB9yOQIw4SlZCZCPJhNKzWebBSbiZBmfjzyGmBpPMC8J9NP9nG2ZA3QAUXnsVOmcyypbROZAoVqBm367ewJZA1B4XH21qd9E3dugyQnkbsZA8kONHnekpjwx5WjzU8t468xuGPrPiv6NaNneuP2AiZAE7K7ZBTXSy0ZAXyQZDZD
spring.datasource.hikari.maximum-pool-size=5

# ============================================
# 5. CREDENCIALES STRIPE API
# ============================================
stripe.api.key=CAMBIAR_POR_LLAVE_REAL
stripe.webhook.secret=CAMBIAR_POR_FIRMA_REAL